#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 80
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_decimal_number = 1,
  sym_absolute_memory_address = 2,
  sym_relative_memory_address = 3,
  anon_sym_PC = 4,
  anon_sym_SP = 5,
  sym_label = 6,
  anon_sym_ADD = 7,
  anon_sym_COMMA = 8,
  anon_sym_SUB = 9,
  anon_sym_MUL = 10,
  anon_sym_DIV = 11,
  anon_sym_MOD = 12,
  anon_sym_AND = 13,
  anon_sym_OR = 14,
  anon_sym_NOT = 15,
  anon_sym_JMP = 16,
  anon_sym_CMP = 17,
  anon_sym_BEQ = 18,
  anon_sym_BNE = 19,
  anon_sym_BGT = 20,
  anon_sym_BLT = 21,
  anon_sym_PUSH = 22,
  anon_sym_POP = 23,
  anon_sym_ST = 24,
  anon_sym_CALL = 25,
  anon_sym_RET = 26,
  anon_sym_SYSCALL = 27,
  sym_source_file = 28,
  sym_register = 29,
  sym_op_value = 30,
  sym_add_op = 31,
  sym_subtract_op = 32,
  sym_multiplication_op = 33,
  sym_division_op = 34,
  sym_modulo_op = 35,
  sym_and_op = 36,
  sym_or_op = 37,
  sym_not_op = 38,
  sym_jump_op = 39,
  sym_compare = 40,
  sym_branch_equals = 41,
  sym_branch_not_equals = 42,
  sym_branch_greater_than = 43,
  sym_branch_less_than = 44,
  sym_push_op = 45,
  sym_pop_op = 46,
  sym_store_op = 47,
  sym_call_op = 48,
  sym_ret_op = 49,
  sym_syscall_op = 50,
  aux_sym_source_file_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_decimal_number] = "decimal_number",
  [sym_absolute_memory_address] = "absolute_memory_address",
  [sym_relative_memory_address] = "relative_memory_address",
  [anon_sym_PC] = "PC",
  [anon_sym_SP] = "SP",
  [sym_label] = "label",
  [anon_sym_ADD] = "ADD",
  [anon_sym_COMMA] = ",",
  [anon_sym_SUB] = "SUB",
  [anon_sym_MUL] = "MUL",
  [anon_sym_DIV] = "DIV",
  [anon_sym_MOD] = "MOD",
  [anon_sym_AND] = "AND",
  [anon_sym_OR] = "OR",
  [anon_sym_NOT] = "NOT",
  [anon_sym_JMP] = "JMP",
  [anon_sym_CMP] = "CMP",
  [anon_sym_BEQ] = "BEQ",
  [anon_sym_BNE] = "BNE",
  [anon_sym_BGT] = "BGT",
  [anon_sym_BLT] = "BLT",
  [anon_sym_PUSH] = "PUSH",
  [anon_sym_POP] = "POP",
  [anon_sym_ST] = "ST",
  [anon_sym_CALL] = "CALL",
  [anon_sym_RET] = "RET",
  [anon_sym_SYSCALL] = "SYSCALL",
  [sym_source_file] = "source_file",
  [sym_register] = "register",
  [sym_op_value] = "op_value",
  [sym_add_op] = "add_op",
  [sym_subtract_op] = "subtract_op",
  [sym_multiplication_op] = "multiplication_op",
  [sym_division_op] = "division_op",
  [sym_modulo_op] = "modulo_op",
  [sym_and_op] = "and_op",
  [sym_or_op] = "or_op",
  [sym_not_op] = "not_op",
  [sym_jump_op] = "jump_op",
  [sym_compare] = "compare",
  [sym_branch_equals] = "branch_equals",
  [sym_branch_not_equals] = "branch_not_equals",
  [sym_branch_greater_than] = "branch_greater_than",
  [sym_branch_less_than] = "branch_less_than",
  [sym_push_op] = "push_op",
  [sym_pop_op] = "pop_op",
  [sym_store_op] = "store_op",
  [sym_call_op] = "call_op",
  [sym_ret_op] = "ret_op",
  [sym_syscall_op] = "syscall_op",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_decimal_number] = sym_decimal_number,
  [sym_absolute_memory_address] = sym_absolute_memory_address,
  [sym_relative_memory_address] = sym_relative_memory_address,
  [anon_sym_PC] = anon_sym_PC,
  [anon_sym_SP] = anon_sym_SP,
  [sym_label] = sym_label,
  [anon_sym_ADD] = anon_sym_ADD,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_SUB] = anon_sym_SUB,
  [anon_sym_MUL] = anon_sym_MUL,
  [anon_sym_DIV] = anon_sym_DIV,
  [anon_sym_MOD] = anon_sym_MOD,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_JMP] = anon_sym_JMP,
  [anon_sym_CMP] = anon_sym_CMP,
  [anon_sym_BEQ] = anon_sym_BEQ,
  [anon_sym_BNE] = anon_sym_BNE,
  [anon_sym_BGT] = anon_sym_BGT,
  [anon_sym_BLT] = anon_sym_BLT,
  [anon_sym_PUSH] = anon_sym_PUSH,
  [anon_sym_POP] = anon_sym_POP,
  [anon_sym_ST] = anon_sym_ST,
  [anon_sym_CALL] = anon_sym_CALL,
  [anon_sym_RET] = anon_sym_RET,
  [anon_sym_SYSCALL] = anon_sym_SYSCALL,
  [sym_source_file] = sym_source_file,
  [sym_register] = sym_register,
  [sym_op_value] = sym_op_value,
  [sym_add_op] = sym_add_op,
  [sym_subtract_op] = sym_subtract_op,
  [sym_multiplication_op] = sym_multiplication_op,
  [sym_division_op] = sym_division_op,
  [sym_modulo_op] = sym_modulo_op,
  [sym_and_op] = sym_and_op,
  [sym_or_op] = sym_or_op,
  [sym_not_op] = sym_not_op,
  [sym_jump_op] = sym_jump_op,
  [sym_compare] = sym_compare,
  [sym_branch_equals] = sym_branch_equals,
  [sym_branch_not_equals] = sym_branch_not_equals,
  [sym_branch_greater_than] = sym_branch_greater_than,
  [sym_branch_less_than] = sym_branch_less_than,
  [sym_push_op] = sym_push_op,
  [sym_pop_op] = sym_pop_op,
  [sym_store_op] = sym_store_op,
  [sym_call_op] = sym_call_op,
  [sym_ret_op] = sym_ret_op,
  [sym_syscall_op] = sym_syscall_op,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_decimal_number] = {
    .visible = true,
    .named = true,
  },
  [sym_absolute_memory_address] = {
    .visible = true,
    .named = true,
  },
  [sym_relative_memory_address] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PC] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SP] = {
    .visible = true,
    .named = false,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_ADD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SUB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MUL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DIV] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MOD] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_JMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BEQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BNE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BGT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BLT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PUSH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CALL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SYSCALL] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [sym_op_value] = {
    .visible = true,
    .named = true,
  },
  [sym_add_op] = {
    .visible = true,
    .named = true,
  },
  [sym_subtract_op] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplication_op] = {
    .visible = true,
    .named = true,
  },
  [sym_division_op] = {
    .visible = true,
    .named = true,
  },
  [sym_modulo_op] = {
    .visible = true,
    .named = true,
  },
  [sym_and_op] = {
    .visible = true,
    .named = true,
  },
  [sym_or_op] = {
    .visible = true,
    .named = true,
  },
  [sym_not_op] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_op] = {
    .visible = true,
    .named = true,
  },
  [sym_compare] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_not_equals] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_greater_than] = {
    .visible = true,
    .named = true,
  },
  [sym_branch_less_than] = {
    .visible = true,
    .named = true,
  },
  [sym_push_op] = {
    .visible = true,
    .named = true,
  },
  [sym_pop_op] = {
    .visible = true,
    .named = true,
  },
  [sym_store_op] = {
    .visible = true,
    .named = true,
  },
  [sym_call_op] = {
    .visible = true,
    .named = true,
  },
  [sym_ret_op] = {
    .visible = true,
    .named = true,
  },
  [sym_syscall_op] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(42);
      ADVANCE_MAP(
        ',', 51,
        'A', 8,
        'B', 12,
        'C', 3,
        'D', 16,
        'J', 22,
        'M', 23,
        'N', 24,
        'O', 30,
        'P', 6,
        'R', 14,
        'S', 25,
        '[', 1,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == 'A') ADVANCE(20);
      if (lookahead == 'M') ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'B') ADVANCE(52);
      END_STATE();
    case 6:
      if (lookahead == 'C') ADVANCE(47);
      if (lookahead == 'O') ADVANCE(28);
      if (lookahead == 'U') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == 'C') ADVANCE(4);
      END_STATE();
    case 8:
      if (lookahead == 'D') ADVANCE(9);
      if (lookahead == 'N') ADVANCE(10);
      END_STATE();
    case 9:
      if (lookahead == 'D') ADVANCE(50);
      END_STATE();
    case 10:
      if (lookahead == 'D') ADVANCE(56);
      END_STATE();
    case 11:
      if (lookahead == 'D') ADVANCE(55);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(29);
      if (lookahead == 'G') ADVANCE(33);
      if (lookahead == 'L') ADVANCE(34);
      if (lookahead == 'N') ADVANCE(13);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(62);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(36);
      END_STATE();
    case 15:
      if (lookahead == 'H') ADVANCE(65);
      END_STATE();
    case 16:
      if (lookahead == 'I') ADVANCE(37);
      END_STATE();
    case 17:
      if (lookahead == 'L') ADVANCE(53);
      END_STATE();
    case 18:
      if (lookahead == 'L') ADVANCE(68);
      END_STATE();
    case 19:
      if (lookahead == 'L') ADVANCE(70);
      END_STATE();
    case 20:
      if (lookahead == 'L') ADVANCE(18);
      END_STATE();
    case 21:
      if (lookahead == 'L') ADVANCE(19);
      END_STATE();
    case 22:
      if (lookahead == 'M') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'O') ADVANCE(11);
      if (lookahead == 'U') ADVANCE(17);
      END_STATE();
    case 24:
      if (lookahead == 'O') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'P') ADVANCE(48);
      if (lookahead == 'T') ADVANCE(67);
      if (lookahead == 'U') ADVANCE(5);
      if (lookahead == 'Y') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'P') ADVANCE(60);
      END_STATE();
    case 27:
      if (lookahead == 'P') ADVANCE(59);
      END_STATE();
    case 28:
      if (lookahead == 'P') ADVANCE(66);
      END_STATE();
    case 29:
      if (lookahead == 'Q') ADVANCE(61);
      END_STATE();
    case 30:
      if (lookahead == 'R') ADVANCE(57);
      END_STATE();
    case 31:
      if (lookahead == 'S') ADVANCE(15);
      END_STATE();
    case 32:
      if (lookahead == 'S') ADVANCE(7);
      END_STATE();
    case 33:
      if (lookahead == 'T') ADVANCE(63);
      END_STATE();
    case 34:
      if (lookahead == 'T') ADVANCE(64);
      END_STATE();
    case 35:
      if (lookahead == 'T') ADVANCE(58);
      END_STATE();
    case 36:
      if (lookahead == 'T') ADVANCE(69);
      END_STATE();
    case 37:
      if (lookahead == 'V') ADVANCE(54);
      END_STATE();
    case 38:
      if (lookahead == ']') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      if (lookahead == ']') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(40);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_decimal_number);
      if (lookahead == ':') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_decimal_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_absolute_memory_address);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_relative_memory_address);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_PC);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SP);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_label);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_ADD);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SUB);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_MUL);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DIV);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_MOD);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_JMP);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_CMP);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_BEQ);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_BNE);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_BGT);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_BLT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_PUSH);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_POP);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_ST);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_CALL);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RET);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_SYSCALL);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 40},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 40},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_decimal_number] = ACTIONS(1),
    [sym_absolute_memory_address] = ACTIONS(1),
    [sym_relative_memory_address] = ACTIONS(1),
    [anon_sym_PC] = ACTIONS(1),
    [anon_sym_SP] = ACTIONS(1),
    [sym_label] = ACTIONS(1),
    [anon_sym_ADD] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_SUB] = ACTIONS(1),
    [anon_sym_MUL] = ACTIONS(1),
    [anon_sym_DIV] = ACTIONS(1),
    [anon_sym_MOD] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_JMP] = ACTIONS(1),
    [anon_sym_CMP] = ACTIONS(1),
    [anon_sym_BEQ] = ACTIONS(1),
    [anon_sym_BNE] = ACTIONS(1),
    [anon_sym_BGT] = ACTIONS(1),
    [anon_sym_BLT] = ACTIONS(1),
    [anon_sym_PUSH] = ACTIONS(1),
    [anon_sym_POP] = ACTIONS(1),
    [anon_sym_ST] = ACTIONS(1),
    [anon_sym_CALL] = ACTIONS(1),
    [anon_sym_RET] = ACTIONS(1),
    [anon_sym_SYSCALL] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(78),
    [sym_add_op] = STATE(3),
    [sym_subtract_op] = STATE(3),
    [sym_multiplication_op] = STATE(3),
    [sym_division_op] = STATE(3),
    [sym_modulo_op] = STATE(3),
    [sym_and_op] = STATE(3),
    [sym_or_op] = STATE(3),
    [sym_not_op] = STATE(3),
    [sym_jump_op] = STATE(3),
    [sym_compare] = STATE(3),
    [sym_branch_equals] = STATE(3),
    [sym_branch_not_equals] = STATE(3),
    [sym_branch_greater_than] = STATE(3),
    [sym_branch_less_than] = STATE(3),
    [sym_push_op] = STATE(3),
    [sym_pop_op] = STATE(3),
    [sym_store_op] = STATE(3),
    [sym_call_op] = STATE(3),
    [sym_ret_op] = STATE(3),
    [sym_syscall_op] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_label] = ACTIONS(5),
    [anon_sym_ADD] = ACTIONS(7),
    [anon_sym_SUB] = ACTIONS(9),
    [anon_sym_MUL] = ACTIONS(11),
    [anon_sym_DIV] = ACTIONS(13),
    [anon_sym_MOD] = ACTIONS(15),
    [anon_sym_AND] = ACTIONS(17),
    [anon_sym_OR] = ACTIONS(19),
    [anon_sym_NOT] = ACTIONS(21),
    [anon_sym_JMP] = ACTIONS(23),
    [anon_sym_CMP] = ACTIONS(25),
    [anon_sym_BEQ] = ACTIONS(27),
    [anon_sym_BNE] = ACTIONS(29),
    [anon_sym_BGT] = ACTIONS(31),
    [anon_sym_BLT] = ACTIONS(33),
    [anon_sym_PUSH] = ACTIONS(35),
    [anon_sym_POP] = ACTIONS(37),
    [anon_sym_ST] = ACTIONS(39),
    [anon_sym_CALL] = ACTIONS(41),
    [anon_sym_RET] = ACTIONS(43),
    [anon_sym_SYSCALL] = ACTIONS(45),
  },
  [2] = {
    [sym_add_op] = STATE(2),
    [sym_subtract_op] = STATE(2),
    [sym_multiplication_op] = STATE(2),
    [sym_division_op] = STATE(2),
    [sym_modulo_op] = STATE(2),
    [sym_and_op] = STATE(2),
    [sym_or_op] = STATE(2),
    [sym_not_op] = STATE(2),
    [sym_jump_op] = STATE(2),
    [sym_compare] = STATE(2),
    [sym_branch_equals] = STATE(2),
    [sym_branch_not_equals] = STATE(2),
    [sym_branch_greater_than] = STATE(2),
    [sym_branch_less_than] = STATE(2),
    [sym_push_op] = STATE(2),
    [sym_pop_op] = STATE(2),
    [sym_store_op] = STATE(2),
    [sym_call_op] = STATE(2),
    [sym_ret_op] = STATE(2),
    [sym_syscall_op] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym_label] = ACTIONS(49),
    [anon_sym_ADD] = ACTIONS(52),
    [anon_sym_SUB] = ACTIONS(55),
    [anon_sym_MUL] = ACTIONS(58),
    [anon_sym_DIV] = ACTIONS(61),
    [anon_sym_MOD] = ACTIONS(64),
    [anon_sym_AND] = ACTIONS(67),
    [anon_sym_OR] = ACTIONS(70),
    [anon_sym_NOT] = ACTIONS(73),
    [anon_sym_JMP] = ACTIONS(76),
    [anon_sym_CMP] = ACTIONS(79),
    [anon_sym_BEQ] = ACTIONS(82),
    [anon_sym_BNE] = ACTIONS(85),
    [anon_sym_BGT] = ACTIONS(88),
    [anon_sym_BLT] = ACTIONS(91),
    [anon_sym_PUSH] = ACTIONS(94),
    [anon_sym_POP] = ACTIONS(97),
    [anon_sym_ST] = ACTIONS(100),
    [anon_sym_CALL] = ACTIONS(103),
    [anon_sym_RET] = ACTIONS(106),
    [anon_sym_SYSCALL] = ACTIONS(109),
  },
  [3] = {
    [sym_add_op] = STATE(2),
    [sym_subtract_op] = STATE(2),
    [sym_multiplication_op] = STATE(2),
    [sym_division_op] = STATE(2),
    [sym_modulo_op] = STATE(2),
    [sym_and_op] = STATE(2),
    [sym_or_op] = STATE(2),
    [sym_not_op] = STATE(2),
    [sym_jump_op] = STATE(2),
    [sym_compare] = STATE(2),
    [sym_branch_equals] = STATE(2),
    [sym_branch_not_equals] = STATE(2),
    [sym_branch_greater_than] = STATE(2),
    [sym_branch_less_than] = STATE(2),
    [sym_push_op] = STATE(2),
    [sym_pop_op] = STATE(2),
    [sym_store_op] = STATE(2),
    [sym_call_op] = STATE(2),
    [sym_ret_op] = STATE(2),
    [sym_syscall_op] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(112),
    [sym_label] = ACTIONS(114),
    [anon_sym_ADD] = ACTIONS(7),
    [anon_sym_SUB] = ACTIONS(9),
    [anon_sym_MUL] = ACTIONS(11),
    [anon_sym_DIV] = ACTIONS(13),
    [anon_sym_MOD] = ACTIONS(15),
    [anon_sym_AND] = ACTIONS(17),
    [anon_sym_OR] = ACTIONS(19),
    [anon_sym_NOT] = ACTIONS(21),
    [anon_sym_JMP] = ACTIONS(23),
    [anon_sym_CMP] = ACTIONS(25),
    [anon_sym_BEQ] = ACTIONS(27),
    [anon_sym_BNE] = ACTIONS(29),
    [anon_sym_BGT] = ACTIONS(31),
    [anon_sym_BLT] = ACTIONS(33),
    [anon_sym_PUSH] = ACTIONS(35),
    [anon_sym_POP] = ACTIONS(37),
    [anon_sym_ST] = ACTIONS(39),
    [anon_sym_CALL] = ACTIONS(41),
    [anon_sym_RET] = ACTIONS(43),
    [anon_sym_SYSCALL] = ACTIONS(45),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(116), 23,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_COMMA,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [26] = 1,
    ACTIONS(118), 23,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_COMMA,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [52] = 1,
    ACTIONS(120), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [77] = 1,
    ACTIONS(122), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [102] = 1,
    ACTIONS(124), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [127] = 1,
    ACTIONS(126), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [152] = 1,
    ACTIONS(128), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [177] = 1,
    ACTIONS(130), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [202] = 1,
    ACTIONS(132), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [227] = 1,
    ACTIONS(134), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [252] = 1,
    ACTIONS(136), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [277] = 1,
    ACTIONS(138), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [302] = 1,
    ACTIONS(140), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [327] = 1,
    ACTIONS(142), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [352] = 1,
    ACTIONS(144), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [377] = 1,
    ACTIONS(146), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [402] = 1,
    ACTIONS(148), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [427] = 1,
    ACTIONS(150), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [452] = 1,
    ACTIONS(152), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [477] = 1,
    ACTIONS(154), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [502] = 1,
    ACTIONS(156), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [527] = 1,
    ACTIONS(158), 22,
      ts_builtin_sym_end,
      sym_label,
      anon_sym_ADD,
      anon_sym_SUB,
      anon_sym_MUL,
      anon_sym_DIV,
      anon_sym_MOD,
      anon_sym_AND,
      anon_sym_OR,
      anon_sym_NOT,
      anon_sym_JMP,
      anon_sym_CMP,
      anon_sym_BEQ,
      anon_sym_BNE,
      anon_sym_BGT,
      anon_sym_BLT,
      anon_sym_PUSH,
      anon_sym_POP,
      anon_sym_ST,
      anon_sym_CALL,
      anon_sym_RET,
      anon_sym_SYSCALL,
  [552] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(14), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [571] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(9), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [590] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(76), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [609] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(56), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [628] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(13), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [647] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(75), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [666] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(74), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [685] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(73), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [704] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(68), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [723] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(71), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [742] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(70), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [761] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(19), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [780] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(25), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [799] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(24), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [818] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(23), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [837] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(77), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [856] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(6), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [875] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(8), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [894] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(17), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [913] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(69), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [932] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(72), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [951] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(66), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [970] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(58), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [989] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(59), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [1008] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(60), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [1027] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(61), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [1046] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(57), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [1065] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(12), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [1084] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(11), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [1103] = 5,
    ACTIONS(160), 1,
      sym_decimal_number,
    STATE(5), 1,
      sym_register,
    STATE(10), 1,
      sym_op_value,
    ACTIONS(164), 2,
      anon_sym_PC,
      anon_sym_SP,
    ACTIONS(162), 3,
      sym_absolute_memory_address,
      sym_relative_memory_address,
      sym_label,
  [1122] = 1,
    ACTIONS(166), 1,
      anon_sym_COMMA,
  [1126] = 1,
    ACTIONS(168), 1,
      anon_sym_COMMA,
  [1130] = 1,
    ACTIONS(170), 1,
      anon_sym_COMMA,
  [1134] = 1,
    ACTIONS(172), 1,
      anon_sym_COMMA,
  [1138] = 1,
    ACTIONS(174), 1,
      anon_sym_COMMA,
  [1142] = 1,
    ACTIONS(176), 1,
      anon_sym_COMMA,
  [1146] = 1,
    ACTIONS(178), 1,
      sym_label,
  [1150] = 1,
    ACTIONS(180), 1,
      sym_label,
  [1154] = 1,
    ACTIONS(182), 1,
      sym_label,
  [1158] = 1,
    ACTIONS(184), 1,
      sym_label,
  [1162] = 1,
    ACTIONS(186), 1,
      anon_sym_COMMA,
  [1166] = 1,
    ACTIONS(188), 1,
      sym_decimal_number,
  [1170] = 1,
    ACTIONS(190), 1,
      anon_sym_COMMA,
  [1174] = 1,
    ACTIONS(192), 1,
      anon_sym_COMMA,
  [1178] = 1,
    ACTIONS(194), 1,
      anon_sym_COMMA,
  [1182] = 1,
    ACTIONS(196), 1,
      anon_sym_COMMA,
  [1186] = 1,
    ACTIONS(198), 1,
      anon_sym_COMMA,
  [1190] = 1,
    ACTIONS(200), 1,
      anon_sym_COMMA,
  [1194] = 1,
    ACTIONS(202), 1,
      anon_sym_COMMA,
  [1198] = 1,
    ACTIONS(204), 1,
      anon_sym_COMMA,
  [1202] = 1,
    ACTIONS(206), 1,
      anon_sym_COMMA,
  [1206] = 1,
    ACTIONS(208), 1,
      anon_sym_COMMA,
  [1210] = 1,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
  [1214] = 1,
    ACTIONS(212), 1,
      sym_decimal_number,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 26,
  [SMALL_STATE(6)] = 52,
  [SMALL_STATE(7)] = 77,
  [SMALL_STATE(8)] = 102,
  [SMALL_STATE(9)] = 127,
  [SMALL_STATE(10)] = 152,
  [SMALL_STATE(11)] = 177,
  [SMALL_STATE(12)] = 202,
  [SMALL_STATE(13)] = 227,
  [SMALL_STATE(14)] = 252,
  [SMALL_STATE(15)] = 277,
  [SMALL_STATE(16)] = 302,
  [SMALL_STATE(17)] = 327,
  [SMALL_STATE(18)] = 352,
  [SMALL_STATE(19)] = 377,
  [SMALL_STATE(20)] = 402,
  [SMALL_STATE(21)] = 427,
  [SMALL_STATE(22)] = 452,
  [SMALL_STATE(23)] = 477,
  [SMALL_STATE(24)] = 502,
  [SMALL_STATE(25)] = 527,
  [SMALL_STATE(26)] = 552,
  [SMALL_STATE(27)] = 571,
  [SMALL_STATE(28)] = 590,
  [SMALL_STATE(29)] = 609,
  [SMALL_STATE(30)] = 628,
  [SMALL_STATE(31)] = 647,
  [SMALL_STATE(32)] = 666,
  [SMALL_STATE(33)] = 685,
  [SMALL_STATE(34)] = 704,
  [SMALL_STATE(35)] = 723,
  [SMALL_STATE(36)] = 742,
  [SMALL_STATE(37)] = 761,
  [SMALL_STATE(38)] = 780,
  [SMALL_STATE(39)] = 799,
  [SMALL_STATE(40)] = 818,
  [SMALL_STATE(41)] = 837,
  [SMALL_STATE(42)] = 856,
  [SMALL_STATE(43)] = 875,
  [SMALL_STATE(44)] = 894,
  [SMALL_STATE(45)] = 913,
  [SMALL_STATE(46)] = 932,
  [SMALL_STATE(47)] = 951,
  [SMALL_STATE(48)] = 970,
  [SMALL_STATE(49)] = 989,
  [SMALL_STATE(50)] = 1008,
  [SMALL_STATE(51)] = 1027,
  [SMALL_STATE(52)] = 1046,
  [SMALL_STATE(53)] = 1065,
  [SMALL_STATE(54)] = 1084,
  [SMALL_STATE(55)] = 1103,
  [SMALL_STATE(56)] = 1122,
  [SMALL_STATE(57)] = 1126,
  [SMALL_STATE(58)] = 1130,
  [SMALL_STATE(59)] = 1134,
  [SMALL_STATE(60)] = 1138,
  [SMALL_STATE(61)] = 1142,
  [SMALL_STATE(62)] = 1146,
  [SMALL_STATE(63)] = 1150,
  [SMALL_STATE(64)] = 1154,
  [SMALL_STATE(65)] = 1158,
  [SMALL_STATE(66)] = 1162,
  [SMALL_STATE(67)] = 1166,
  [SMALL_STATE(68)] = 1170,
  [SMALL_STATE(69)] = 1174,
  [SMALL_STATE(70)] = 1178,
  [SMALL_STATE(71)] = 1182,
  [SMALL_STATE(72)] = 1186,
  [SMALL_STATE(73)] = 1190,
  [SMALL_STATE(74)] = 1194,
  [SMALL_STATE(75)] = 1198,
  [SMALL_STATE(76)] = 1202,
  [SMALL_STATE(77)] = 1206,
  [SMALL_STATE(78)] = 1210,
  [SMALL_STATE(79)] = 1214,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(79),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_register, 1, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_op_value, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiplication_op, 6, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_greater_than, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subtract_op, 6, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_add_op, 6, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_store_op, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compare, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_not_op, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_syscall_op, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_op, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pop_op, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_less_than, 2, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_op, 2, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_push_op, 2, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_or_op, 6, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ret_op, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_equals, 2, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_branch_not_equals, 2, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_division_op, 6, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_modulo_op, 6, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_and_op, 6, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [210] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bluebird_asm(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
